seed: 1684067553
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    graphs, (n_feat, num_classes) = load_graph_classification_dataset(dataname)
  File "/root/models/SMCL/dataset.py", line 178, in load_graph_classification_dataset
    dataset = TUDataset(dataset_name)
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/dgl/data/tu.py", line 327, in __init__
    super(TUDataset, self).__init__(name=name, url=url,
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/dgl/data/dgl_dataset.py", line 321, in __init__
    super(DGLBuiltinDataset, self).__init__(
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/dgl/data/dgl_dataset.py", line 113, in __init__
    self._load()
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/dgl/data/dgl_dataset.py", line 204, in _load
    self.process()
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/dgl/data/tu.py", line 333, in process
    loadtxt(self._file_path("A"), delimiter=",").astype(int))
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/dgl/data/utils.py", line 39, in loadtxt
    df = pd.read_csv(path, delimiter=delimiter, header=None)
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/envs/graph/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/root/.dgl/REDDIT-MULTI5K/REDDIT-MULTI5K/REDDIT-MULTI5K_A.txt'
